### ISSUE TITLE
reserved parameters missing from importer map

### ISSUE THREAD

**Issue by moraru** [virtualcell/vcell#651]
We no longer import parameters with reserved names (e.g. _T_, _F_)  as duplicates with mangled name (unless their value is different from default) - see PR #622.

However, they still need to have an SBase wrapper abd be put into the importer map pointing to the actual vcell parameter so they can be identified if they are targets for changes etc.

**Comment by danv61** [comment]
Fixed in b475eb9

**Comment by moraru** [comment]
Not fixed.  Still no Sbase wrapper created for them and not put into Sbm

**Comment by moraru** [comment]
Fixed in c923484343e8fea95a7a947d205e2952fd920f9e

**Comment by moraru** [comment]
pushed to master
